experiment_name: train
dataset:
  class_dict_path: "/media/sadi/Vol_2/IUB_research_local/Satellite/data/deepglobe_kaggle/archive"
  full_image_path: "/media/sadi/Vol_2/IUB_research_local/Satellite/data/deepglobe_kaggle/archive/train"
  full_label_path: "/media/sadi/Vol_2/IUB_research_local/Satellite/data/deepglobe_kaggle/archive/train"
  patches_image_path: "/media/sadi/Vol_2/IUB_research_local/Satellite/data/deepglobe_kaggle/archive/patches/sat"
  patches_label_path: "/media/sadi/Vol_2/IUB_research_local/Satellite/data/deepglobe_kaggle/archive/patches/mask"
  train_image_ids: "/media/sadi/Vol_2/IUB_research_local/Satellite/CCDS-SatelliteSegmentation/dataloaders/dummy_split/train_img_ids.txt"
  train_label_ids: "/media/sadi/Vol_2/IUB_research_local/Satellite/CCDS-SatelliteSegmentation/dataloaders/dummy_split/train_label_ids.txt"
  val_image_ids: "/media/sadi/Vol_2/IUB_research_local/Satellite/CCDS-SatelliteSegmentation/dataloaders/deepglobe_split0/val_img_ids.txt"
  val_label_ids: "/media/sadi/Vol_2/IUB_research_local/Satellite/CCDS-SatelliteSegmentation/dataloaders/deepglobe_split0/val_label_ids.txt"
  input_size: 512
  no_of_patches: 16
  img_convert: RGB
  label_convert: RGB
model:
  num_classes: 7
  mode: sup
  supervised_w: 1
  backbone: "deeplab_v3+"
  layers: 50
  out_dim: 256
optimizer:
  optimizer_fn: Adam
  initial_lr: 0.0001
logs:
  use_wandb: False
  wandb_project_name: CCDS-SatelliteSegentation
  wandb_entity: sadimohammad
  run_name:
  save_local_logs: True
  local_logs_path: ../logs
train_setup:
  checkpoints_path: ../ckpts
  batch_size: 4
  epochs: 2
  device: gpu
  device_ids: 0
  dataparallel: False
  model_weight_load: False
  best_valid_score: 0.0
  model_weight_path: 2019-09-17 12:22:27.449158_epoch-3_dice-0.0.pth
  loss: dice_coeff_loss
  metric: iou_calc
  use_thld_for_valid: True #threshold for validation
  thld_for_valid: 0.5 #threshold for validation
  save_best_model: True